/**
 * Capability model for the Capability Discovery Engine.
 *
 * The engine's guiding principle is that it does not classify products — it infers what a
 * person is capable of supplying, as a continuously updated set of probabilistic hypotheses
 * (CDE "Guiding principle", §7, §8).
 *
 * Two things follow from that and shape everything here:
 *
 *  1. Nothing is ever true or false. Every capability carries a confidence, and confidence
 *     only ever moves — it is never replaced by a verdict.
 *  2. Capability identifiers are never invented. Product capabilities are GS1 GPC codes;
 *     service capabilities come from a registry that deduplicates by meaning. See the
 *     Capability Resolver (CDE "Capability Resolver").
 */

/** Which vocabulary a canonical capability identifier belongs to. */
export const CAPABILITY_DOMAINS = ['product', 'service'] as const;

export type CapabilityDomain = (typeof CAPABILITY_DOMAINS)[number];

/**
 * A canonical capability reference.
 *
 * `product` identifiers are GPC codes (e.g. `10003500`); `service` identifiers are registry
 * slugs (e.g. `svc_generator_repair`). Both are looked up, never generated by a model.
 */
export interface CapabilityRef {
  readonly domain: CapabilityDomain;
  readonly id: string;
  /** Human-readable name, for explanations and logs. Never used as an identifier. */
  readonly name: string;
}

/**
 * How much a single statement tells us (CDE "Every statement has different information
 * density").
 *
 * "We sell things" is almost useless; "We stock Schneider breakers, armored cable, MCCBs and
 * conduit fittings" is extremely informative. Density scales how far a piece of evidence is
 * allowed to move belief.
 */
export const INFORMATION_DENSITIES = ['very_low', 'low', 'medium', 'high', 'very_high'] as const;

export type InformationDensity = (typeof INFORMATION_DENSITIES)[number];

/** Multiplier applied to evidence strength, by density. */
const DENSITY_WEIGHT: Readonly<Record<InformationDensity, number>> = {
  very_low: 0.15,
  low: 0.4,
  medium: 0.7,
  high: 1,
  very_high: 1.3,
};

/**
 * Where a piece of evidence came from.
 *
 * Source matters independently of density: marketplace behaviour outranks anything a vendor
 * says about themselves, because "marketplace evidence always overrides AI assumptions"
 * (CME §12) and because actions are harder to misreport than descriptions (CDE Principle 6).
 */
export const EVIDENCE_SOURCES = [
  'onboarding_statement',
  'clarification_answer',
  'post_onboarding_answer',
  'business_name',
  'inventory_update',
  'vendor_correction',
  'request_accepted',
  'request_rejected',
  'match_completed',
  'customer_confirmation',
  'llm_inference',
] as const;

export type EvidenceSource = (typeof EVIDENCE_SOURCES)[number];

/**
 * Reliability weight per source, in the same units as density.
 *
 * The ordering is the important part, not the exact values: a vendor confirming a real
 * customer request ("yes, I have it") is worth far more than an LLM's guess expanding a
 * broad statement, and a vendor's explicit correction outranks everything because it is the
 * one signal that is unambiguously intentional.
 */
const SOURCE_RELIABILITY: Readonly<Record<EvidenceSource, number>> = {
  vendor_correction: 1.6,
  customer_confirmation: 1.5,
  match_completed: 1.4,
  request_accepted: 1.2,
  request_rejected: 1.2,
  inventory_update: 1.1,
  post_onboarding_answer: 1,
  clarification_answer: 1,
  onboarding_statement: 0.9,
  business_name: 0.5,
  // Bootstrap only. Hypotheses the model invented must never harden into fact on their own
  // (CDE §10: "Evidence never disappears. Only confidence changes.").
  llm_inference: 0.35,
};

/**
 * One immutable observation and what it implies (CDE §11).
 *
 * Evidence is never edited or deleted. Recomputing belief from the full evidence history is
 * what makes the DNA auditable and lets inference rules improve retroactively.
 */
export interface EvidenceObject {
  readonly id: string;
  readonly vendorId: string;
  readonly source: EvidenceSource;
  readonly observedAt: Date;
  /** Exactly what the vendor said or did. */
  readonly originalText: string;
  /** The interpreted meaning, before resolution to canonical ids. */
  readonly normalizedMeaning: string;
  readonly informationDensity: InformationDensity;
  /** Capabilities this observation speaks to, each with its own direction and strength. */
  readonly supports: readonly CapabilitySignal[];
  /** Why the engine drew this conclusion, kept for explainability. */
  readonly reasoning: string;
  readonly conversationId?: string;
  readonly workflowId?: string;
}

/**
 * A single capability claim inside an evidence object.
 *
 * `strength` in [0,1] is how directly the observation implies the capability: naming a
 * product outright is near 1, an archetype expansion is far lower.
 */
export interface CapabilitySignal {
  readonly capability: CapabilityRef;
  readonly strength: number;
  /**
   * False when the observation is evidence *against* the capability — a rejected request or
   * a correction ("no, I don't sell TVs").
   *
   * Negative evidence is why the engine can distinguish "probably not" from "unknown"
   * (CDE Principle 17), which most systems collapse into a single "no".
   */
  readonly positive: boolean;
}

/**
 * The engine's current belief about one capability (CDE §9).
 *
 * Belief is stored as log-odds rather than probability because evidence then accumulates by
 * addition: each new observation adds its weight, and no observation has to know about any
 * other. Converting to a probability is a presentation concern.
 */
export interface CapabilityBelief {
  readonly capability: CapabilityRef;
  /** Sum of weighted evidence, in log-odds. Negative means "probably not". */
  readonly logOdds: number;
  /** Probability in (0,1), derived from {@link logOdds}. */
  readonly confidence: number;
  /** How many evidence objects have touched this capability. */
  readonly evidenceCount: number;
  readonly lastObservedAt: Date;
  /** True when the capability came from expansion rather than direct observation. */
  readonly inferred: boolean;
}

/**
 * The living representation of a vendor (CDE §8).
 *
 * Never rebuilt, only evolved. `completeness` is deliberately an estimate rather than a
 * percentage of some fixed checklist — there is no complete profile (CDE Principle 8).
 */
export interface VendorDna {
  readonly vendorId: string;
  readonly beliefs: readonly CapabilityBelief[];
  /** Free-text products, services and brands the vendor named, kept verbatim. */
  readonly declaredProducts: readonly string[];
  readonly declaredServices: readonly string[];
  readonly brands: readonly string[];
  /** Rolling natural-language description used for embedding and explanations. */
  readonly summary: string;
  readonly evidenceCount: number;
  readonly updatedAt: Date;
}

/**
 * Prior for a capability that some evidence has already touched.
 *
 * The reference class matters. Across ~6,500 GPC bricks a vendor supplies a few dozen, so the
 * prior for a capability picked at random is under 0.01 — but a belief only exists here once
 * something has pointed at it, and that is a very different population. Starting every
 * mentioned capability from near-zero would mean a vendor could say "I sell electrical
 * materials" and still be judged 6% likely to sell electrical materials.
 *
 * So this is the prior for "mentioned or implied at all": still sceptical, still requiring
 * evidence to reach a useful level, but not a hole that one honest statement cannot climb out
 * of. Capabilities nobody has mentioned are simply absent, which is stronger than any prior.
 */
export const PRIOR_CONFIDENCE = 0.15;

/** Half-life of evidence influence. */
const EVIDENCE_HALF_LIFE_DAYS = 365;

/** Floor on decay, so old evidence fades but never becomes worthless. */
const MIN_DECAY_FACTOR = 0.25;

/**
 * Ceiling on a single observation's contribution, in log-odds.
 *
 * Sized so that one strong, direct, high-density observation lands a capability around 0.8 —
 * confident enough to match on — while still leaving room for later evidence to move it, and
 * never reaching certainty on its own. A single "yes, I have it" must not be unfalsifiable by
 * the ten rejections that might follow.
 */
const MAX_SIGNAL_LOG_ODDS = 4;

export function toLogOdds(probability: number): number {
  const clamped = Math.min(Math.max(probability, 1e-6), 1 - 1e-6);
  return Math.log(clamped / (1 - clamped));
}

export function toProbability(logOdds: number): number {
  return 1 / (1 + Math.exp(-logOdds));
}

/**
 * Weight of one signal, in log-odds, before decay.
 *
 * Multiplicative in density, source reliability and directness: a vague statement from a weak
 * source about a loosely-implied capability should move belief barely at all, and the product
 * of three sub-one factors expresses that naturally.
 */
export function signalLogOdds(
  signal: CapabilitySignal,
  source: EvidenceSource,
  density: InformationDensity,
): number {
  const magnitude =
    MAX_SIGNAL_LOG_ODDS *
    SOURCE_RELIABILITY[source] *
    DENSITY_WEIGHT[density] *
    Math.min(Math.max(signal.strength, 0), 1);

  const capped = Math.min(magnitude, MAX_SIGNAL_LOG_ODDS);

  return signal.positive ? capped : -capped;
}

/**
 * Attenuation applied to evidence as it ages.
 *
 * A vendor who stocked generators two years ago may not today, so old evidence should not
 * outvote recent behaviour — but it is still real evidence, hence the floor.
 */
export function decayFactor(observedAt: Date, now: Date): number {
  const ageDays = Math.max(0, (now.getTime() - observedAt.getTime()) / 86_400_000);
  const decayed = Math.pow(0.5, ageDays / EVIDENCE_HALF_LIFE_DAYS);
  return Math.max(MIN_DECAY_FACTOR, decayed);
}

/**
 * Recomputes beliefs from the full evidence history.
 *
 * Deriving belief rather than mutating it in place means a change to the weighting rules
 * applies retroactively to every vendor, and the same evidence always yields the same DNA —
 * which is what makes the engine's output reproducible and auditable.
 */
export function deriveBeliefs(evidence: readonly EvidenceObject[], now: Date): readonly CapabilityBelief[] {
  const accumulator = new Map<
    string,
    {
      capability: CapabilityRef;
      logOdds: number;
      count: number;
      lastObservedAt: Date;
      everDirect: boolean;
    }
  >();

  const prior = toLogOdds(PRIOR_CONFIDENCE);

  for (const item of evidence) {
    const decay = decayFactor(item.observedAt, now);

    for (const signal of item.supports) {
      const key = `${signal.capability.domain}:${signal.capability.id}`;
      const existing = accumulator.get(key);

      const contribution = signalLogOdds(signal, item.source, item.informationDensity) * decay;
      // Anything at or above this strength is a direct observation rather than an expansion.
      const direct = signal.strength >= 0.8;

      if (existing === undefined) {
        accumulator.set(key, {
          capability: signal.capability,
          logOdds: prior + contribution,
          count: 1,
          lastObservedAt: item.observedAt,
          everDirect: direct,
        });
        continue;
      }

      existing.logOdds += contribution;
      existing.count += 1;
      existing.everDirect = existing.everDirect || direct;
      if (item.observedAt > existing.lastObservedAt) existing.lastObservedAt = item.observedAt;
    }
  }

  return [...accumulator.values()]
    .map((entry) => ({
      capability: entry.capability,
      logOdds: entry.logOdds,
      confidence: toProbability(entry.logOdds),
      evidenceCount: entry.count,
      lastObservedAt: entry.lastObservedAt,
      inferred: !entry.everDirect,
    }))
    .sort((a, b) => b.confidence - a.confidence);
}

/**
 * Uncertainty of a belief, in bits (CDE "Capability Entropy").
 *
 * Maximal at 0.5 — the engine genuinely does not know — and near zero at either extreme.
 * The Curiosity Engine spends its limited questions where this is highest *and* where
 * resolving it would most improve matching.
 */
export function capabilityEntropy(confidence: number): number {
  const p = Math.min(Math.max(confidence, 1e-6), 1 - 1e-6);
  return -(p * Math.log2(p) + (1 - p) * Math.log2(1 - p));
}

/** Beliefs strong enough to advertise the vendor for. */
export function confidentCapabilities(dna: VendorDna, threshold: number): readonly CapabilityBelief[] {
  return dna.beliefs.filter((belief) => belief.confidence >= threshold);
}

/**
 * Capabilities worth asking about: uncertain, and not yet settled by direct observation.
 *
 * Ordered by entropy so the highest-value question comes first (CDE Principle 4 —
 * "questions compete").
 */
export function highestEntropyCapabilities(dna: VendorDna, limit: number): readonly CapabilityBelief[] {
  return [...dna.beliefs]
    .filter((belief) => belief.inferred)
    .sort((a, b) => capabilityEntropy(b.confidence) - capabilityEntropy(a.confidence))
    .slice(0, limit);
}
